# PostgreSQL - WSL Compatible Configuration
# Usage: docker-compose up -d

services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    networks:
      data-platform-dev:
        ipv4_address: 172.30.50.10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-datauser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-datapass}
      POSTGRES_DB: ${POSTGRES_DB:-datawarehouse}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../../logs/postgres:/postgres-logs
    command: >
      bash -c "
      echo '=== Starting PostgreSQL for Development ===';
      echo 'Database: ${POSTGRES_DB:-datawarehouse}';
      echo 'User: ${POSTGRES_USER:-datauser}';
      echo 'Log directory: /postgres-logs';
      
      # Create log directory if it doesn't exist
      mkdir -p /postgres-logs;
      chmod 755 /postgres-logs;
      
      exec docker-entrypoint.sh postgres
      "
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-datauser} -d ${POSTGRES_DB:-datawarehouse}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

# Volumes - Sadeleştirilmiş
volumes:
  postgres-data:
    driver: local

# Network
networks:
  data-platform-dev:
    name: data-platform-dev
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
